name: awesome_image
description: "A Flutter package for image processing and manipulation."

version: 0.0.2
homepage: https://github.com/oussamamth1/awesome_image.git

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  palette_generator: ^0.3.3+3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # ... rest of your flutter configuration
